### ISSUE TITLE
Different display, same controller issue

### ISSUE THREAD

**Issue by julienlemusicien** [firexx/SSD1803a_I2C_4x20#1]
Hello Firexx,
I am trying to use the library you wrote with 16x4 character displays (EA DOGS164N-A, https://www.mouser.fr/datasheet/2/127/dogs164e-1532335.pdf ), since they use the same SSD1803A controller as your MIDAS display.
For now, I can't make it work. My poor skills in writing or editing libraries don't allow me to find the cause of the problem. I can only set the contrast, but text won't print on the display.
Could you help me please ?
Thank you a lot for your work and time.
Julien.

**Comment by firexx** [comment]
How can i help you?

**Comment by julienlemusicien** [comment]
I don't understand what I am doing wrong. I think my display is correctly connected to my Teensy 3.5, since I can use lcd.setContrast() from your library to change the contrast of the display.
The problem is, I can't really do anything else : lcd.print() and lcd.println() does not seem to work in my case, my display seems stuck with all of its pixels on (with lcd.display() ) or off (with lcd.noDisplay() ) at the same time.
I thought you could point me to the right direction, if you have any idea of where my problem comes from ?
Thank you.

**Comment by firexx** [comment]
did you tried the examples?

**Comment by julienlemusicien** [comment]
Yes, I tried all of them. I used a custom resetPin (#0 on my Teensy), and changed the lcd.begin(20,4); to lcd.begin(16,4); since my display is 16x4.

**Comment by firexx** [comment]
look
void SSD1803a_I2C::send_command(uint8_t cmd)
{
	Wire.beginTransmission(_i2caddr);
	Wire.write(0x00); // control byte for command
	Wire.write(cmd); // command clear display
	Wire.endTransmission();
}

void SSD1803a_I2C::send_byte(uint8_t val)
{
	Wire.beginTransmission(_i2caddr);
	Wire.write(0x40); // control byte for data
	Wire.write(val); // data byte
	Wire.endTransmission();
}
the contrast using send_command. print using the send_byte. the difference is only of write 00 for command and 40 for writing data.

i would suggest you write more data as only one hello world like
lcd.setCursor(0,0);
for (i = 'A' ; i <= 'Z'; ++i)
  lcd.write(i);

and look what happened

i dont known how i can help you because i don't have a hardware...

**Comment by firexx** [comment]
if you set a contrast do you see the black rectagles? and they will be darker with more contrast value?

**Comment by firexx** [comment]
other posibility you rewrite the void SSD1803a_I2C::init() function in library like it provided on datasheet. see INITIALIZATION EXAMPLE table. use directly the values instead of constants i defined on the begin off cpp file. it has to be like:
send_command(0x3A);
send_command(0x09);
send_command(0x06);
send_command(0x1E);
send_command(0x39);
send_command(0x1B);
send_command(0x6C);
send_command(0x56);
send_command(0x7A);
send_command(0x38);
send_command(0x0F);

**Comment by julienlemusicien** [comment]
Oh, your last idea saved me ! After rewriting the init() function in the library as you suggested, lcd.write() and lcd.print both work :)
I don't know exactly what was the issue, so I am going to read carefully your example, your library and the controller datasheet.

Thank you so much.

**Comment by firexx** [comment]
if you know why it does not work, please write me. we can try to specify the right configuration that work on both displays.

**Comment by julienlemusicien** [comment]
This is what I know for now : 
1/ I had to set the contrast manually at the begining of my sketch with lcd.setContrast(0); Before that, the contrast was too high and the screen was all black.
2/ I don't fully understand what each command does in the initialization function you gave me earlier, but they work for me, unlike the ones already in the init() function in the library, which don't. I will try to get things clear during the next few days.

**Comment by Muratkok** [comment]
Hello Firex,
I am working on this panel. I can set the contrast of the screen and send all commands to the screen. However, I cant send the right data to screen:


void send_byte(uint8_t row,uint8_t col,uint8_t *buffer){
     row = ((row-1) *  0x20);
     send_command(0x84+row+col);//setting DDRAM register address
     I2C1_start();
     I2C1_Wr(LedSlaveAddress);
     I2C1_Wr(0x40);//data register address
     I2C1_Wr(*buffer);//data
     I2C1_stop();
}

send_byte(1,0,'A');

This function doesn't work. The screen doesn't display the 'A' character. I would be very pleased if you help me.

**Comment by firexx** [comment]
what is the implementation? did you tried the libraries examples? Pls open new issue because @julienlemusicien will be noted every time we write here.

**Comment by Muratkok** [comment]
I want the screen to display the data I sent. For instance  'A' character.
Also, I am using a pic microcontroller. I made some modifications to the
code for applying on pic microcontroller.
I send the 'A'' character but the screen display this character, as you
see the image.

Andrej Kostrov ***@***.***>, 2 Ara 2021 Per, 12:12 tarihinde
şunu yazdı:

**Comment by Muratkok** [comment]
https://user-images.githubusercontent.com/82180410/144406643-90453d29-d621-4f76-a0a3-775350036af8.jpeg
