### ISSUE TITLE
Different display

### ISSUE THREAD

**Issue by Muratkok** [firexx/SSD1803a_I2C_4x20#3]
My problem is the different display.  I send the 'A' character but the screen display a different character.

https://user-images.githubusercontent.com/82180410/144410730-f5acc5c5-42fa-4d0d-904e-9cbfc9473a46.jpeg

**Comment by firexx** [comment]
try to send (BYTE)('A' + offset) with pause of 1 sec. or print the series of letters with char code offset. look for the documentation of your display. may be it is a wrong charset burned into the rom of display.

**Comment by Muratkok** [comment]
Firstly, I put a delay of 1 sec; but nothing has changed.
     send_byte(1,1,'A');
      Delay_ms(1000);

You said that there might be a problem with ROM. That is why I coded the ROM selection.

void set_character(){
  send_command(0x3A);
  send_command(0x72);
  send_value(0x00);  //romA selected
  send_command(0x38);
}

But Nothing has changed again

1_sec_delay
https://user-images.githubusercontent.com/82180410/144554046-28375723-8f62-4c65-a1f9-f27348ba5acc.jpg

ROMB_selected
https://user-images.githubusercontent.com/82180410/144554067-2d89914c-a003-4aa3-b601-1eea65cff4e0.jpg

ROMA_ROMC_selected
https://user-images.githubusercontent.com/82180410/144554110-f27827f6-95e4-4d1e-894e-d211076047a5.jpeg

here is the documentation  of the panel:
https://www.lcd-module.com/fileadmin/eng/pdf/doma/dogs164e.pdf

**Comment by Muratkok** [comment]
If I explain the ROMB selection, the Character has changed, however, it still displays a different character.

**Comment by firexx** [comment]
i mean something like 
for (byte i=0; i<0xff; ++i){
     send_byte(1+i%20,1,i):
     Delay_ms(100);
}

and look if any codes prints the correct letters. cyrillic letters are also correct letters :-D

**Comment by Muratkok** [comment]
It worked.
UART1_Write_Text("HELLO WORLD");
   for ( counter10=31; counter10<46; ++counter10){
          send_byte(1,size,counter10);
          size++;
          if(counter10 == 45)
          size = 0;
          //Delay_ms(1);
          }
UART1_Write_Text(THIS IS ME);
      for ( counter10=47; counter10<62; ++counter10){
          send_byte(2,size,counter10);
          size++;
          if(counter10 == 61)
          size = 0;
          //Delay_ms(1);
          }
However, it must be tried to find what the right address is.

https://user-images.githubusercontent.com/82180410/144804413-45fc1948-6f50-48ac-bca6-9664e7cf26f0.jpg
